// My own practice
console.log("Munir");
let firstName ="Hania";
console.log(firstName);
let famousPerson:string="Quaid e Azam";
var quote = `"All Pakistanis Are Equal"`;
console.log(`${famousPerson} said that:${quote}`);
let fName = "mahad";
console.log(fName);
let stripped = fName.trim();
console.log(stripped);
let practice = "\n\t Waseem \t\n";
console.log(practice);
console.log(5+3);
console.log(10-2);
console.log(4*2);
console.log(16/2);
let fatherName = "Wamiq";
console.log(fatherName.toUpperCase());
let teacher:string="Sir Safdar";
console.log(teacher.toLowerCase());
