// My own practice
console.log("Munir");
var firstName = "Hania";
console.log(firstName);
var famousPerson = "Quaid e Azam";
var quote = "\"All Pakistanis Are Equal\"";
console.log("".concat(famousPerson, " said that:").concat(quote));
var fName = "mahad";
console.log(fName);
var stripped = fName.trim();
console.log(stripped);
var practice = "\n\t Waseem \t\n";
console.log(practice);
console.log(5 + 3);
console.log(10 - 2);
console.log(4 * 2);
console.log(16 / 2);
var fatherName = "Wamiq";
console.log(fatherName.toUpperCase());
var teacher = "Sir Safdar";
console.log(teacher.toLowerCase());
